// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uriktazmqlzglbhzjcqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyaWt0YXptcWx6Z2xiaHpqY3FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDQ3NjAsImV4cCI6MjA2ODY4MDc2MH0.weFdkG84kxNGB8isQ4rkT6NUzJNsSUun0JXVFvaZcQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});